### ISSUE TITLE
Support imports having multiple lines (incl. conditionals, comments, and/or annotations)

### ISSUE THREAD

**Issue by JCKodel** [aziznal/dart-import-sorter#49]
Before:

```dart
import 'package:kfx_dependency_injection/kfx_dependency_injection/platform_info.dart';
import 'package:mockito/annotations.dart';

// This is required:
import 'package:mockito/mockito.dart';

@GenerateNiceMocks([MockSpec<IAppSettingsRepository>(), MockSpec<IToDoRepository>()])
import "test_environment.mocks.dart";
```

After sorting:
```dart
import 'package:kfx_dependency_injection/kfx_dependency_injection/platform_info.dart';
import 'package:mockito/annotations.dart';

import 'package:mockito/mockito.dart';

import "test_environment.mocks.dart";
```

Both the comment and `@GenerateNiceMocks` are deleted when the sort occurs.

This package should stick `//` and `@` lines to the same place they were before.

Or, at least, give us some option to ignore certain files, such as:

```json
"dartImport.excludeGeneratedFiles": [
    "g.dart",
    "config.dart",
    "freezed.dart",
    "test_environment.dart"
  ],
```

**Comment by aziznal** [comment]
Hi. Thank you for your detailed feedback. I'm working on an addition that'll fix both the issues you mentioned here as well as in #48. But please bear with me because I'm sick as heck right now :mask:

So the way I plan on supporting this is to make it such that when an import is detected, any lines above it and below it which are not other imports or line breaks will also be grabbed as part of that import's raw body, but the actual sorting will only be done by using the import's body still. 

I'm not 100% sure on what you mean by "ignore certain files".  Can you explain that a bit more?

**Comment by JCKodel** [comment]
> I'm not 100% sure on what you mean by "ignore certain files". Can you explain that a bit more?

The VS plugin DartImport has an option to ignore certain glob patterns, but I think this will not be useful here, so, please, ignore that bit =)

**Comment by aziznal** [comment]
Just made a [new release](https://github.com/aziznal/dart-import-sorter/releases/tag/0.3.0). You shouldn't be encountering any more problems. Let me know if you have any issues!
